export interface BillingTerm {
  id: string;
  term: string;
  definition: string;
  example: string;
  learnMoreUrl: string;
  keywords: string[];
}

export const DOCS_BASE_URL = 'https://docs.stellarbill.example';

export const GLOSSARY: BillingTerm[] = [
  {
    id: 'mrr',
    term: 'Monthly Recurring Revenue',
    definition:
      'The predictable revenue your business earns from active subscriptions each month, before one-off fees, credits, or refunds.',
    example:
      'If 100 customers pay $50/month, your MRR is $5,000 regardless of when the payments actually land.',
    learnMoreUrl: `${DOCS_BASE_URL}/glossary/mrr`,
    keywords: ['mrr', 'monthly', 'recurring', 'revenue'],
  },
  {
    id: 'arr',
    term: 'Annual Recurring Revenue',
    definition:
      'A normalized projection of your recurring revenue for a full year. It is typically MRR × 12.',
    example:
      'A $2,000 MRR business runs at a $24,000 ARR run rate even before annual contracts are considered.',
    learnMoreUrl: `${DOCS_BASE_URL}/glossary/arr`,
    keywords: ['arr', 'annual', 'recurring', 'revenue', 'run rate'],
  },
  {
    id: 'proration',
    term: 'Proration',
    definition:
      'The way a subscription charge is adjusted when a plan changes mid-cycle, so you only pay for the portion of the period used.',
    example:
      'Switching from a $30 plan to a $40 plan halfway through the month credits the $15 you already paid and charges $20 for the remainder.',
    learnMoreUrl: `${DOCS_BASE_URL}/glossary/proration`,
    keywords: ['proration', 'prorated', 'pro rata', 'mid-cycle', 'adjustment'],
  },
  {
    id: 'dunning',
    term: 'Dunning',
    definition:
      'The automated retry process that attempts to collect a failed charge again on a schedule before a subscription is canceled.',
    example:
      'After a card is declined, dunning retries the payment at 1 day, 3 days, and 7 days, emailing the customer between attempts.',
    learnMoreUrl: `${DOCS_BASE_URL}/glossary/dunning`,
    keywords: ['dunning', 'retry', 'failed charge', 'declined', 'recovery'],
  },
  {
    id: 'churn',
    term: 'Churn',
    definition:
      'The rate at which customers cancel or fail to renew within a given period. It measures lost recurring revenue.',
    example:
      'If 5 of 100 subscribers cancel in a month, your customer churn rate is 5% for that month.',
    learnMoreUrl: `${DOCS_BASE_URL}/glossary/churn`,
    keywords: ['churn', 'cancellation', 'cancel', 'attrition', 'retention'],
  },
  {
    id: 'expansion',
    term: 'Expansion Revenue',
    definition:
      'Additional recurring revenue generated by existing customers through upgrades, add-ons, or increased usage.',
    example:
      'A customer who moves from the Basic to the Pro plan contributes expansion revenue without adding a new account.',
    learnMoreUrl: `${DOCS_BASE_URL}/glossary/expansion`,
    keywords: ['expansion', 'upsell', 'upgrade', 'add-on', 'growth'],
  },
  {
    id: 'downgrade',
    term: 'Downgrade',
    definition:
      'Moving a subscription to a lower-priced plan or a reduced feature set, usually effective at the next billing period.',
    example:
      'Moving a subscription from Business to Pro at $20 less per month is a downgrade with a $20 MRR loss.',
    learnMoreUrl: `${DOCS_BASE_URL}/glossary/downgrade`,
    keywords: ['downgrade', 'downsell', 'reduce', 'lower plan'],
  },
  {
    id: 'prepaid',
    term: 'Prepaid Balance',
    definition:
      'A credit balance funded in advance that usage-based charges are drawn from during a billing period.',
    example:
      'After topping up $100, usage draws down the balance each day; when it runs low you are prompted to top up again.',
    learnMoreUrl: `${DOCS_BASE_URL}/glossary/prepaid`,
    keywords: ['prepaid', 'balance', 'credit', 'top up', 'drawdown'],
  },
  {
    id: 'billing-cycle',
    term: 'Billing Cycle',
    definition:
      'The recurring interval at which a subscription is charged, such as monthly or annually.',
    example:
      'A plan with a monthly billing cycle charges on the same day each month until the subscription is paused or canceled.',
    learnMoreUrl: `${DOCS_BASE_URL}/glossary/billing-cycle`,
    keywords: ['billing cycle', 'cadence', 'interval', 'period', 'frequency'],
  },
  {
    id: 'invoice',
    term: 'Invoice',
    definition:
      'A formal itemized statement of charges for a billing period, including line items, taxes, and the amount due.',
    example:
      'A customer paying $29/month receives an invoice listing the plan price, tax, and the total charged to their balance.',
    learnMoreUrl: `${DOCS_BASE_URL}/glossary/invoice`,
    keywords: ['invoice', 'receipt', 'statement', 'bill', 'itemized'],
  },
  {
    id: 'usage',
    term: 'Usage-Based Billing',
    definition:
      'A pricing model where the amount charged scales with measured consumption rather than a flat fee.',
    example:
      'An API plan that charges $0.05 per 1,000 requests bills differently each cycle based on actual request volume.',
    learnMoreUrl: `${DOCS_BASE_URL}/glossary/usage`,
    keywords: ['usage', 'metered', 'consumption', 'variable', 'pay as you go'],
  },
  {
    id: 'seat',
    term: 'Seats',
    definition:
      'Licensed user slots on a subscription. Each seat typically grants one member access and carries a per-seat price.',
    example:
      'A team plan priced at $8 per seat charges $80/month when you have 10 active members.',
    learnMoreUrl: `${DOCS_BASE_URL}/glossary/seat`,
    keywords: ['seat', 'per-seat', 'license', 'user', 'member'],
  },
];

export function getTerm(id: string): BillingTerm | undefined {
  return GLOSSARY.find((t) => t.id === id);
}
